# Dependabot configuration for automated dependency updates
# See: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Rust dependencies (Cargo)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "wyattroersma"  # Add your GitHub username
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      # Group minor and patch updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Allow specific updates
    allow:
      - dependency-type: "all"
    # Ignore specific dependencies if needed
    ignore:
      # Example: - dependency-name: "tokio"
      #            versions: ["1.x"]
    rebase-strategy: "auto"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "wyattroersma"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group all action updates together
      actions:
        patterns:
          - "*"
    
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "wyattroersma"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"

# Security updates are enabled by default and run separately from the above schedule