# Pre-commit hooks configuration
# Install with: pip install pre-commit && pre-commit install

repos:
  # Rust formatting and linting
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Cargo format
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: cargo-check
        name: Cargo check
        entry: cargo check --all-features
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: cargo-clippy
        name: Cargo clippy
        entry: cargo clippy --all-features -- -W warnings
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: cargo-test
        name: Cargo test
        entry: cargo test --lib --bins
        language: system
        types: [rust]
        pass_filenames: false
        stages: [push]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        exclude: \.md$
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: ^\.github/

  # Security checks
  - repo: local
    hooks:
      - id: cargo-audit
        name: Cargo audit
        entry: cargo audit
        language: system
        pass_filenames: false
        stages: [push]

  # License header check (optional)
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        files: \.rs$
        args:
          - --license-filepath
          - .license-header.txt  # Create this file if you want license headers
          - --comment-style
          - //
        exclude: ^(target/|examples/|benches/)

# Configuration
default_stages: [commit]
fail_fast: false
verbose: true